[mysql]
host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com" 
port = 4000
database = "test" 
user = "2BaCvcfcbcnEhqr.root"
password = "8IBGYhPwYO4Q2N4z"

[resend]
api_key = "re_CiXbj6zf_AN5gCW7WVsatczXWt8NmAFKj"

[gemini]
api_key =  "AIzaSyAMAfqRzAwMFMsrSVdyNM968io4tKSNX3Y"
